spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC
    username: root
    password: CTpmqjV99F
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: DeveloperSmelovEA
    password: DevelopSomething
    email: DeveloperSmelovEA@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005

captcha:
  delete:
    hours: 1
  length: 4
  width: 100
  height: 35
  secretCode:
      length: 35

password:
  min:
    length: 6
  restore:
    code:
      length: 20

file:
  name:
    length : 20
  image:
    dir: src/main/resources/upload
  photo:
    dir: src/main/resources/upload/avatar
    size: 5_000_000
    width: 36
    height: 36

comment:
  text:
    min:
      length: 3
post:
  title:
    min:
      length: 3
  text:
    min:
      length: 50




