spring.datasource.url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC
spring.datasource.username: root  
spring.datasource.password: CTpmqjV99F
spring.jpa.hibernate.ddl-auto: none
spring.jpa.show-sql: true

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005

authService.captchaDeleteHours: 1

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 10MB

image.filepath: src/main/resources/upload

avatar.filePath: src/main/resources/upload/avatar
avatar.fileSize: 5


spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: DeveloperSmelovEA
spring.mail.password: DevelopSomething
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.properties.mail.smtp.starttls.required: true