spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/forum?serverTimezone=UTC}
    username: root
    password: CTpmqjV99F
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.yandex.ru
    port: 465
    username: DeveloperSmelovEA@yandex.ru
    password: DevelopSomething
    protocol: smtps
  flyway:
    baselineOnMigrate: true

server:
  port: ${PORT:8080}

mail:
  email: DeveloperSmelovEA@yandex.ru
  debug: true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005
  url: smelov-java-skillbox.herokuapp.com

captcha:
  delete:
    hours: 1
  length: 4
  width: 100
  height: 35
  secretCode:
      length: 35

password:
  min:
    length: 6
  restore:
    code:
      length: 20

file:
  path: /uploads
  name:
    length : 20
  image:
  photo:
    size: 5_000_000
    width: 36
    height: 36

cloud:
  image:
    url: cloudinary://942858327361784:NCZQ3GuY9FPG3fv3p0BpuzrzaeM@db20eod0q

storage:
  mode: cloud

comment:
  text:
    length:
      min: 3
      max: 200

post:
  announce:
    length:
      max: 150
  title:
    length:
      min: 3
      max: 255
  text:
    length:
      min: 50
      max: 1000




